[build]
  command = ""            # no build on Netlify; we commit prebuilt docs
  publish = "docs"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"